version: '3.0'

services:
  bin:
    build:
      context: .
      dockerfile: Dockerfile
    command: "go test -v"
    ports:
      - "22:22"
    # links:
    #   - nginx-proxy
    #   - fakes3
    volumes:
      - .:/go/src/app
    env_file: .secrets

  # fakes3:
  #   image: lphoward/fake-s3
  #   ports:
  #     - "4569:4569"
  #   environment:
  #     - VIRTUAL_HOST=s3.amazonaws.com
  #     - VIRTUAL_PROTO=https

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-certs:/etc/nginx/certs
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
