version: '3.0'

services:
  bin:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run *.go"
    ports:
      - "22:22"
    volumes:
      - .:/go/src/app
    env_file: .secrets
