version: '3.0'

services:
  bin:
    build:
      context: .
      dockerfile: Dockerfile
    command: "go run ."
    ports:
      - "22:22"
      - "8080:8080"
    links:
      - postgres
    volumes:
      - .:/go/src/app
    env_file: .secrets

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
