version: '3.0'

services:
  lib: &default
    build:
      context: .
      dockerfile: Dockerfile
    command: go test
    volumes:
      - .:/go/src/app

  bin:
    <<: *default
    command: /bin/sh -c "cd ./bin && go run main.go"
    ports:
      - "22:22"
      - "2022:2022"
